### ISSUE TITLE
android.view.ContextThemeWrapper cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by muhammadimran021** [Kaopiz/KProgressHUD#52]
java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at com.kaopiz.kprogresshud.KProgressHUD.dismiss(KProgressHUD.java:329)
        at crm.pixtech.com.CustomDialoges.CustomContactInfoDialog.ShowDialog(CustomContactInfoDialog.java:159)
        at crm.pixtech.com.CustomDialoges.CustomContactInfoDialog.access$100(CustomContactInfoDialog.java:39)
        at crm.pixtech.com.CustomDialoges.CustomContactInfoDialog$1.onSuccess(CustomContactInfoDialog.java:135)
        at crm.pixtech.com.NetworkRequest.Network.lambda$GET_REQUEST$2$Network(Network.java:288)
        at crm.pixtech.com.NetworkRequest.Network$$Lambda$2.onResponse(Unknown Source)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:78)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by tuanna-hsp** [comment]
Thank you for reporting.
Fix has been merged to the master branch.
